import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { AuthProvider } from "@/context/AuthContext";
import { ThemeProvider } from "@/context/ThemeContext";
import Navbar from "@/components/Navbar";
import { JobProvider } from "@/context/JobContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Apply Frame",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ThemeProvider>
          <AuthProvider>
            <JobProvider>
              <Navbar />
              {children}
            </JobProvider>
          </AuthProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
